:schedule:
  Compats::CheckAllUnchecked:
    cron: "*/10 * * * *"
  Maintenance::CheckGitBranches:
    cron: 0 * * * *
  Maintenance::CheckPendingCompats:
    cron: 0 * * * *
  RefreshSitemap:
    cron: 0 1 * * *
