default: &default
  url: <%= ENV["REDIS_URL"] %>
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  timeout: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
